version: '2'

services:
  web:
    image: fleetr/traccar
    restart: unless-stopped
    ports:
      - "80:8082"
      - "10026:5005"
      - "10027:5027"

  traccar-mqtt:
    image: fleetr/traccar2mqtt
    environment:
      MQTT_URL: mqtt://mqtt:1883
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - /data/traccar2mqtt/data:/app/data

  db:
    image: postgres:9
    restart: unless-stopped
    environment:
      POSTGRES_DB: traccar
      POSTGRES_USER: traccar
      POSTGRES_PASSWORD: traccar@fleetr
    ports:
      - "5432:5432"
    volumes:
      - /data/traccar/postgres/data:/var/lib/postgresql/data

  mqtt:
    image: villlem/mqtt-server:latest
    restart: unless-stopped
    ports:
     - "10028:1883"

  mongo:
    image: mongo:3
    restart: unless-stopped
    command: --replSet rs0
    ports:
     - "27017:27017"
     - "28017:28017"
    volumes:
     - /data/fleetr/mongo/data:/data/db


networks:
  default:
    driver: bridge
