version: '2'

services:
  web:
    image: fleetr/traccar
    restart: unless-stopped
    depends_on:
      - db
      - mqtt
    ports:
      - "80:8082"
      - "10026:5055"
      - "10027:5027"

  db:
    image: postgres:9
    restart: unless-stopped
    environment:
      POSTGRES_DB: traccar
      POSTGRES_USER: traccar
      POSTGRES_PASSWORD: traccar@fleetr
    ports:
      - "5432:5432"
    volumes:
      - /data/traccar/postgres/data:/var/lib/postgresql/data

  mqtt:
    image: greyarch/mosquitto
    restart: unless-stopped
    ports:
     - "10028:1883"

  mongo:
    image: mongo:3
    restart: unless-stopped
    command: --replSet rs0
    ports:
     - "27017:27017"
     - "28017:28017"
    volumes:
     - /data/fleetr/mongo/data:/data/db


networks:
  default:
    driver: bridge
