version: '2'

services:
  web:
    image: fleetr/traccar
    restart: unless-stopped
    ports:
      - "80:8082"
      - "10026:5005"
      - "10027:5027"

  traccar-mqtt:
    image: fleetr/traccar2mqtt
    environment:
      MQTT_URL:
    restart: unless-stopped
    ports:
      - "4000:4000"

  db:
    image: postgres:9
    restart: unless-stopped
    environment:
      POSTGRES_DB: traccar
      POSTGRES_USER: traccar
      POSTGRES_PASSWORD: traccar@fleetr
    ports:
      - "5432:5432"
    volumes:
      - /data/traccar/postgres/data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
